name: vlisemod-reviewer-reproducibility
channels:
  - conda-forge
dependencies:
  - python=3.13.12
  - gemmi=0.7.5
  - biopython=1.88
  - numpy=2.4.4
  - scipy=1.18.0
  - pandas=3.0.3
  - rdkit=2026.3.1
  - openbabel=3.2.1
  - pip
  - pip:
      - pdbe-arpeggio==1.4.4
