#!/usr/bin/env python3
"""Report a ligand-side, locally clear exit-vector cue for one occurrence.

This is a read-only diagnostic for the atom-level geometry already generated by
the CIF-native PROTACability pipeline.  It deliberately does *not* predict
linker length, E3-ligase compatibility, ternary-complex formation, or protein
degradation.  Its only question is whether an already eligible ligand
attachment atom points away from the observed pocket and has a locally clear
forward corridor in the deposited structure.

The score and label mirror ``12_build_protacability.py`` so a proposed UI can
be checked against existing database evidence before any production change.

Examples
--------
python TOOLS/assess_exit_vector_cue.py --database viral_data.db \
    --pdb 3EKY --ligand DR7 --chain A --residue 100

python TOOLS/assess_exit_vector_cue.py --database viral_data.db \
    --ligand-instance-id 59418 --json
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path
from typing import Any, Iterable


METHOD_LABEL = "ligand-exit-vector-cue-v1"
DEFAULT_RAY_LENGTH_A = 8.0
DEFAULT_RAY_RADIUS_A = 2.0
INTERPRETATION = (
    "Ligand-side local modification-site cue only; it does not predict linker "
    "length, E3-ligase compatibility, ternary-complex formation, or degradation."
)


def cue_label(candidate_count: int, outward_count: int, clear_count: int) -> str:
    """Return the production-compatible human-readable cue label."""
    if clear_count:
        return "Locally clear ligand exit-vector cue"
    if outward_count:
        return "Outward ligand atom cue with local forward obstruction"
    if candidate_count:
        return "Candidate attachment atoms without an outward exit-vector cue"
    return "No candidate ligand attachment atom"


def assess_atoms(atoms: Iterable[dict[str, Any]]) -> dict[str, Any]:
    """Calculate the cue from attachment-site rows without modifying the DB.

    A candidate is the pipeline's chemically/structurally screened attachment
    atom.  ``points_away_from_pocket`` is derived from the ligand-centroid to
    atom direction relative to the ligand-centroid to pocket-centroid direction.
    ``local_corridor_clear`` means no protein atom was found inside the sampled
    forward cylinder (default: 8 A long, 2 A radius).
    """
    rows = list(atoms)
    candidates = [row for row in rows if int(row["candidate_attachment_atom"] or 0) == 1]
    outward = [row for row in candidates if int(row["points_away_from_pocket"] or 0) == 1]
    clear = [row for row in outward if int(row["local_corridor_clear"] or 0) == 1]
    candidate_count = len(candidates)
    outward_count = len(outward)
    clear_count = len(clear)
    score = round(
        (40.0 * outward_count / candidate_count + 60.0 * clear_count / candidate_count)
        if candidate_count else 0.0,
        2,
    )
    return {
        "method": METHOD_LABEL,
        "candidate_attachment_atom_count": candidate_count,
        "outward_candidate_count": outward_count,
        "locally_clear_outward_candidate_count": clear_count,
        "exit_vector_score": score,
        "cue": cue_label(candidate_count, outward_count, clear_count),
        "local_sampling": {
            "ray_length_a": _uniform_number(rows, "forward_clearance_a", DEFAULT_RAY_LENGTH_A),
            "ray_radius_a": DEFAULT_RAY_RADIUS_A,
            "meaning": "A clear corridor reaches the sampled cap; it is not clearance beyond that cap.",
        },
        "interpretation": INTERPRETATION,
        "attachment_atoms": [_atom_payload(row) for row in sorted(candidates, key=_atom_sort_key)],
    }


def _uniform_number(rows: list[dict[str, Any]], key: str, fallback: float) -> float:
    """Infer the sampled cap when clear rows provide it, otherwise use default."""
    values = {
        round(float(row[key]), 4)
        for row in rows
        if int(row["local_corridor_clear"] or 0) == 1 and row[key] is not None
    }
    return values.pop() if len(values) == 1 else fallback


def _atom_sort_key(row: dict[str, Any]) -> tuple[float, str]:
    return (-float(row["attachment_priority_score"] or 0.0), str(row["atom_site_id"] or ""))


def _atom_payload(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "atom_site_id": row["atom_site_id"],
        "atom": row["exact_atom"],
        "element": row["element"],
        "smiles_atom_indices": row["smiles_atom_indices"],
        "attachment_priority_score": row["attachment_priority_score"],
        "attachment_priority_tier": row["attachment_priority_tier"],
        "chemical_context": row["chemical_context"],
        "solvent_exposed": bool(row["solvent_exposed"]),
        "strong_contact_count": int(row["strong_contact_count"] or 0),
        "points_away_from_pocket": bool(row["points_away_from_pocket"]),
        "outward_score": row["outward_score"],
        "local_corridor_clear": bool(row["local_corridor_clear"]),
        "forward_clearance_a": row["forward_clearance_a"],
        "forward_obstruction_count": row["forward_obstruction_count"],
    }


def find_instances(db: sqlite3.Connection, args: argparse.Namespace) -> list[sqlite3.Row]:
    if args.ligand_instance_id:
        rows = db.execute(
            """SELECT i.ligand_instance_id,s.entry_id,i.deposited_model_num,i.label_comp_id,
                      i.auth_asym_id,i.auth_seq_id,i.insertion_code_normalized
                 FROM ligand_instances i JOIN structures s ON s.structure_id=i.structure_id
                WHERE i.ligand_instance_id=?""",
            (args.ligand_instance_id,),
        ).fetchall()
    else:
        if not (args.pdb and args.ligand):
            raise ValueError("provide --ligand-instance-id or both --pdb and --ligand")
        where = ["UPPER(s.entry_id)=UPPER(?)", "UPPER(i.label_comp_id)=UPPER(?)"]
        values: list[Any] = [args.pdb, args.ligand]
        if args.chain:
            where.append("UPPER(i.auth_asym_id)=UPPER(?)")
            values.append(args.chain)
        if args.residue is not None:
            where.append("i.auth_seq_id=?")
            values.append(str(args.residue))
        rows = db.execute(
            """SELECT i.ligand_instance_id,s.entry_id,i.deposited_model_num,i.label_comp_id,
                      i.auth_asym_id,i.auth_seq_id,i.insertion_code_normalized
                 FROM ligand_instances i JOIN structures s ON s.structure_id=i.structure_id
                WHERE """ + " AND ".join(where) + " ORDER BY i.ligand_instance_id",
            values,
        ).fetchall()
    if not rows:
        raise ValueError("no matching ligand occurrence found")
    return rows


def latest_attachment_rows(db: sqlite3.Connection, ligand_instance_id: int) -> list[dict[str, Any]]:
    latest = db.execute(
        "SELECT MAX(run_id) FROM protacability_attachment_sites WHERE ligand_instance_id=?",
        (ligand_instance_id,),
    ).fetchone()[0]
    if latest is None:
        raise ValueError("no attachment-site evidence exists; run stages 10–13 first")
    return [dict(row) for row in db.execute(
        """SELECT * FROM protacability_attachment_sites
             WHERE ligand_instance_id=? AND run_id=? ORDER BY attachment_site_id""",
        (ligand_instance_id, latest),
    )]


def assess_instance(db: sqlite3.Connection, instance: sqlite3.Row) -> dict[str, Any]:
    result = assess_atoms(latest_attachment_rows(db, instance["ligand_instance_id"]))
    result["occurrence"] = {
        "ligand_instance_id": instance["ligand_instance_id"],
        "pdb_code": instance["entry_id"],
        "model": instance["deposited_model_num"],
        "ligand": instance["label_comp_id"],
        "chain": instance["auth_asym_id"],
        "residue": instance["auth_seq_id"],
        "insertion_code": instance["insertion_code_normalized"] or None,
    }
    return result


def print_report(result: dict[str, Any]) -> None:
    occurrence = result["occurrence"]
    print("Ligand exit-vector cue (read-only diagnostic)")
    print(
        f"Occurrence: {occurrence['pdb_code']} / {occurrence['ligand']} "
        f"{occurrence['chain']} {occurrence['residue']} (instance {occurrence['ligand_instance_id']})"
    )
    print(f"Cue: {result['cue']}")
    print(f"Exit-vector score: {result['exit_vector_score']:.2f}/100")
    print(
        "Candidates: "
        f"{result['candidate_attachment_atom_count']} screened; "
        f"{result['outward_candidate_count']} outward; "
        f"{result['locally_clear_outward_candidate_count']} locally clear outward"
    )
    sample = result["local_sampling"]
    print(
        f"Local clearance sample: {sample['ray_length_a']:g} A forward, "
        f"{sample['ray_radius_a']:g} A radius. {sample['meaning']}"
    )
    print("\nRanked candidate attachment atoms:")
    if not result["attachment_atoms"]:
        print("  None")
    for atom in result["attachment_atoms"]:
        direction = "outward" if atom["points_away_from_pocket"] else "not outward"
        clearance = "clear" if atom["local_corridor_clear"] else "obstructed"
        print(
            f"  {atom['atom']} (site {atom['atom_site_id']}): {direction}, {clearance}; "
            f"priority {float(atom['attachment_priority_score']):.1f}; "
            f"chemistry {atom['chemical_context']}"
        )
    print(f"\nInterpretation: {result['interpretation']}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", required=True, type=Path, help="Path to the V-LiSEMOD SQLite database.")
    selector = parser.add_argument_group("occurrence selector")
    selector.add_argument("--ligand-instance-id", type=int)
    selector.add_argument("--pdb")
    selector.add_argument("--ligand")
    selector.add_argument("--chain")
    selector.add_argument("--residue")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not args.database.is_file():
        print(f"database not found: {args.database}", file=sys.stderr)
        return 2
    try:
        with sqlite3.connect(f"file:{args.database.resolve()}?mode=ro", uri=True) as db:
            db.row_factory = sqlite3.Row
            results = [assess_instance(db, instance) for instance in find_instances(db, args)]
    except (sqlite3.Error, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps(results[0] if len(results) == 1 else results, indent=2, sort_keys=True))
    else:
        for index, result in enumerate(results):
            if index:
                print("\n" + "=" * 72)
            print_report(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
